name: 'Webprovisions Deploy Action'
description: 'Deploy distribution'
inputs:
  minio_access_key:
    description: 'Minio Access Key'
    required: true
  minio_secret_key:
    description: 'Minio Secret Key'
    required: true
  minio_host:
    description: 'Minio Host'
    required: true
  wp_api:
    description: 'Webprovisions API URL'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.minio_access_key}}
    - ${{ inputs.minio_secret_key}}
    - ${{ inputs.minio_host}}
    - ${{ inputs.wp_api}}
